version: '3.7'
services:
    dbpg:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=userpg
          - POSTGRES_PASSWORD=passwordpg
        ports:
          - 5432:5432
        volumes:
          - ./seed/vaccinationsdb.sql:/docker-entrypoint-initdb.d/vaccinationsdb.sql          
    web-node:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env
        depends_on:
          - dbpg